# Generated by Django 5.2.1 on 2025-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlename', models.CharField(max_length=64)),
                ('content1', models.TextField(max_length=1024)),
                ('content2', models.TextField(max_length=1024)),
                ('content3', models.TextField(max_length=1024)),
                ('source', models.TextField(max_length=500)),
                ('planetimage1', models.ImageField(upload_to='planet_images/')),
                ('planetimage2', models.ImageField(upload_to='planet_images/')),
                ('planetimage3', models.ImageField(upload_to='planet_images/')),
                ('button1content', models.TextField(max_length=32)),
                ('button2content', models.TextField(max_length=32)),
                ('button3content', models.TextField(max_length=32)),
                ('animationcolor', models.CharField(max_length=64)),
            ],
        ),
    ]
