# Generated by Django 5.2.1 on 2025-05-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetinfo',
            name='button4content',
            field=models.TextField(default='Default button 4 text', max_length=32),
        ),
    ]
