# Generated by Django 5.2.1 on 2025-05-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_planetinfo_button4content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetinfo',
            name='planetimage1',
            field=models.FileField(upload_to='planet_images/'),
        ),
        migrations.AlterField(
            model_name='planetinfo',
            name='planetimage2',
            field=models.FileField(upload_to='planet_images/'),
        ),
        migrations.AlterField(
            model_name='planetinfo',
            name='planetimage3',
            field=models.FileField(upload_to='planet_images/'),
        ),
    ]
